import { config } from "dotenv";
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

config({ path: resolve(process.cwd(), ".env.local") });

function escPem(pem: string): string {
  return pem.replace(/\n/g, "\\n");
}

const { privateKey, publicKey } = generateKeyPairSync("rsa", {
  modulusLength: 2048,
  publicKeyEncoding: { type: "spki", format: "pem" },
  privateKeyEncoding: { type: "pkcs8", format: "pem" },
});

const sessionSecret = randomBytes(32).toString("hex");
const encryptionKey = randomBytes(32).toString("hex");

const contents = `# Noirly Identity local development environment
# Generated by scripts/generate-env.ts — do not commit real secrets.

NODE_ENV=development
MONGODB_URI=mongodb://127.0.0.1:27017/noirly-identity
APP_URL=http://localhost:3000
OIDC_ISSUER=http://localhost:3000

SESSION_SECRET=${sessionSecret}
ENCRYPTION_KEY=${encryptionKey}

JWT_PRIVATE_KEY="${escPem(privateKey)}"
JWT_PUBLIC_KEY="${escPem(publicKey)}"
JWT_KEY_ID=noirly-identity-1

EMAIL_PROVIDER=development
`;

const target = resolve(process.cwd(), ".env.local");
if (existsSync(target) && process.argv.includes("--force") === false) {
  console.log(".env.local already exists. Pass --force to overwrite.");
  process.exit(0);
}

writeFileSync(target, contents, "utf8");
console.log(`Wrote ${target}`);
